# local profile that allows to run Broker, Core and UI on a single machine with more verbose logging

server:
  port: 8082

address: "localhost"
protocol: http

http:
  mappers:
    jsonPrettyPrint: true
    
udp:
  port: 8080

websocket:
  endpointUrl: ws-measur
  allowedOrigin: "*"
  topicDestinationPrefix: /topica
  allThingsTopic: /topica/all
  alertsTopicPrefix: /topica/alerts
  allAlertsTopic: /topica/alerts/all

keepalive:
  timeInterval: 60000
  timeout: 1000

appKey: dummy

registry:
  allowRegistration: true
  allowOverride: true
  interfaces:
    - id: lightning-service
      contract:
        services:
          - name: switchLight
            id: switchLight
            endpoint: /switchLight
            parameters:
              - name: colour
                type: INTEGER
              - name: intensity
                type: INTEGER